### ISSUE TITLE
update to DPoP authentication. Legacy being deprecated.

### ISSUE THREAD

**Issue by ewingson** [o-development/ochat-client#48]
Solid recently had an update from legacy auth to the use of DPoP auth.

We noticed that your app still is using the old auth.

We'd like to encourage you to switch to the new auth using the Demonstrating Proof of Posession technology.

Our motivation for the update was using the standard OIDC-way. 

- CSS is and will only use DPoP.
- For a transition period NSS is able to use both legacy and DPoP.
- SolidOS has been migrated and only uses DPoP.

Javascript libraries using the new authentication methods include :
- [Inrupt's](https://github.com/inrupt/solid-client-authn-js) solid-client-authn-browser for the browser and solid-client-authn-node.
- and [solid-node-client](https://github.com/solid/solid-node-client) for nodejs.
- To obtain a token for nodejs app login, you will also need [Inrupt's generate-oidc-token](https://github.com/inrupt/generate-oidc-token).

Some simple examples of javascript app using the DPoP auth can be found here
- https://github.com/0dataapp/hello/tree/main/solid.
- or https://github.com/jeff-zucker/solid-ide (simple migration).

The list of apps using the new DPoP authorization can be followed here [dpop-status](https://solidproject.solidcommunity.net/Team/dpop-migration).

Just let us know if we can assist you on switching your app at https://gitter.im/solid/app-development or https://forum.solidproject.org

From solid team

**Comment by jaxoncreed** [comment]
This is actually the client for `https://liqid.chat` not `https://chat.o.team`. Liqid chat is compatible with the new auth. Consider it to be the spiritual successor to chat.o.team.

**Comment by ewingson** [comment]
thank u. I'll update the status immediately.

**Comment by ewingson** [comment]
FYI, trying liqid.chat with solidweb.me gives me
`{"message":"Cannot save to auth map. Session is not logged in.","metadata":{}}`

[edit] the console says 
![Bildschirmfoto_2022-01-23_21-25-56](https://user-images.githubusercontent.com/36561948/150696796-8e35b2e5-8168-4808-b329-e97a7193ca81.png)
did I handle something wrong ?

**Comment by jaxoncreed** [comment]
Have you logged into liqid chat before? Try resetting your localstorage.

But, in general, I'm not happy with the way I implemented the auth. I needed to do a hack to get it to work on the mobile phone. I'm working through a better mobile implementation.

**Comment by ewingson** [comment]
trying to clear the cache had no effect,
but using solidweb.org didn't work, too (Unauthorized, 401) that *should* work and hints at a problem with my client ??

**Comment by ewingson** [comment]
solidweb.org now works at the second trial, but still the console on solidweb.me gives the 401 and the above message

**Comment by jaxoncreed** [comment]
Hmm. That's strange, but unfortunately this is a "won't fix" for now. I'm working on a new set of dev tools that will do mobile login a completely different way, so until those are implemented liqid chat will have to remain glitchy.
